-- Alerts generated by ingestion, analytics, or manual operators
CREATE TABLE IF NOT EXISTS alerts (
  alert_id        TEXT PRIMARY KEY,
  device_id       TEXT NOT NULL,
  profile_id      TEXT,
  alert_type      TEXT NOT NULL,
  severity        TEXT NOT NULL DEFAULT 'info',
  status          TEXT NOT NULL DEFAULT 'open',
  summary         TEXT,
  description     TEXT,
  metadata_json   TEXT,
  acknowledged_at TEXT,
  resolved_at     TEXT,
  resolved_by     TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  FOREIGN KEY(device_id) REFERENCES devices(device_id)
);

CREATE INDEX IF NOT EXISTS ix_alerts_device_status
  ON alerts(device_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_alerts_profile_created
  ON alerts(profile_id, created_at DESC);

-- Commissioning checklist runs tied to individual devices
CREATE TABLE IF NOT EXISTS commissioning_runs (
  run_id         TEXT PRIMARY KEY,
  device_id      TEXT NOT NULL,
  profile_id     TEXT,
  status         TEXT NOT NULL DEFAULT 'draft',
  started_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  completed_at   TEXT,
  checklist_json TEXT,
  notes          TEXT,
  performed_by   TEXT,
  report_url     TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  FOREIGN KEY(device_id) REFERENCES devices(device_id)
);

CREATE INDEX IF NOT EXISTS ix_commissioning_device
  ON commissioning_runs(device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_commissioning_profile
  ON commissioning_runs(profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_commissioning_status
  ON commissioning_runs(status, updated_at DESC);

-- Audit trail of privileged changes and lifecycle events
CREATE TABLE IF NOT EXISTS audit_trail (
  audit_id      TEXT PRIMARY KEY,
  actor_id      TEXT NOT NULL,
  actor_email   TEXT,
  actor_name    TEXT,
  action        TEXT NOT NULL,
  entity_type   TEXT,
  entity_id     TEXT,
  metadata_json TEXT,
  ip_address    TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS ix_audit_entity
  ON audit_trail(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_actor
  ON audit_trail(actor_id, created_at DESC);
